### ISSUE TITLE
can you prevent it from closing by dragging down?

### ISSUE THREAD

**Issue by gbmiranda** [flipkart-incubator/ContentSheet#11]
someway??

Att,
Gabriel

**Comment by rajatgupta26** [comment]
Hi,
As of now there's no way to do that. I'll try and accommodate this in next release.

**Comment by rajatgupta26** [comment]
"enablePanGesture" setting exposed in 0.2-beta-2. Working on some other fixes and features. Will make a release soon.
Thanks

**Comment by karimabdelhameed** [comment]
@rajatgupta26  : Please Add it ASAP , and thank you for your great efforts , I'm pending on my project for this feature , so please help us 👍  :)
