### ISSUE TITLE
Custom height and background view

### ISSUE THREAD

**Issue by llKoull** [flipkart-incubator/ContentSheet#37]
Hi!

I've been trying to do a modal view with this library and all is loading correctly but i'm not being able to change the collapsed height and the color of the background view (i don't want to use a blur background view and the alpha of the regular black layer is too dark).

I tried to do a custom background view with clear background color but it doesn't work, the background shows pure black if i do so.

Anyone can help me?

Thanks and best regards!

**Comment by rajatgupta26** [comment]
Hi, thanks for using this library. Try customising "`backgroundView`" and "`blurBackground`" properties of content sheet.

**Comment by llKoull** [comment]
Hi @shyamakirala !

I finally changed the background color, but i can't define the height of the collapsed height withoud modifying the library. If i don't change the height, the view shows incorrectly on iPhone X, iPhone 11, ...

Can i do that without modifying your code?

Thanks and best regards!
